export { default as minecraftLogo } from "../assets/icons/Minecraft-Logo.png"
export { default as spotifyLogo } from "../assets/icons/Spotify_hero_logo.svg"
export { default as spotifyLogoDark } from "../assets/icons/Spotify_hero_logo_dark.svg"
export { default as darkBuhooLogo } from "../assets/icons/black-background.png"
export { default as brandGithub } from "../assets/icons/brand-github.svg"
export { default as brandLinkedin } from "../assets/icons/brand-linkedin.svg"
export { default as file } from "../assets/icons/file.svg"
export { default as iconoPage } from "../assets/icons/icono_hero.png"
export { default as locationIcon } from "../assets/icons/location_icon.svg"
export { default as mail } from "../assets/icons/mail.svg"
export { default as whiteBuhooLogo } from "../assets/icons/white-background.png"

export { default as arrow } from "../assets/image/arrow.png"
export { default as mashImage } from "../assets/image/mash.png"
export { default as pencilCircle } from "../assets/image/pencil_circle.png"
export { default as profilePhoto } from "../assets/image/profle_photo.png"

export { default as buhooAppGround } from "../assets/proyects/Buhoo_app.png"
export { default as spotifyAppGround } from "../assets/proyects/Spotify-clon.png"
export { default as minecraftAppGround } from "../assets/proyects/minecraft-screenshot.png"

export { default as AboutMe } from "../assets/image/Aboutme-dark.png"
